name: Build C++ Game on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install mingw -y
          set PATH=C:\tools\mingw64\bin;%PATH%

      - name: Build the game
        run: g++ -Iinclude -Ilib -o startship.exe src/*.cpp lib/tinyxml2.cpp

      - name: Test the build
        run: startship.exe || echo "Run failed, continuing for debugging purposes"
